### ISSUE TITLE
Logo contest 

### ISSUE THREAD

**Issue by ym1234** [buffet/W#2]
Comment 1 for
https://cdn.discordapp.com/attachments/393586170652655616/596336810712498197/vv.png
or 2 for 
https://cdn.discordapp.com/attachments/361916911682060289/592089899906105417/342xjl.png

**Comment by josephsdavid** [comment]
12 - combine them

**Comment by ym1234** [comment]
Okay, our third contestant https://cdn.discordapp.com/attachments/393586170652655616/596339729817927680/vv.png

**Comment by buffet** [comment]
Can we do this a bit more seriously? I'd like to this language, and community, flourish.

**Comment by lemonnn-8** [comment]
1 is great 
you should go with that

**Comment by buffet** [comment]
Closed by #7
